#ifndef DDC_HANDLER_H
#define DDC_HANDLER_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct MonitorInfo {
  char *id;
  char *name;
  uint16_t brightness;
} MonitorInfo;

/**
 *     Get a list of monitors.
 *
 *    # Arguments
 *
 *    * `out_count` - The number of monitors.
 *
 *    # Returns
 *
 *    * `monitors` - A pointer to the monitors.
 */
struct MonitorInfo *ddc_get_monitors(uintptr_t *out_count);

/**
 *     Free the memory allocated by `ddc_get_monitors`.
 *
 *    # Arguments
 *
 *    * `monitors` - The pointer to the monitors to free.     * `count` - The number of monitors to free.
 */
void ddc_free_monitors(struct MonitorInfo *monitors,
                       uintptr_t count);

/**
 *     Set the brightness of a monitor.
 *
 *    # Arguments
 *
 *    * `percent` - The brightness to set the monitor to.     * `monitor_id` - The id of the monitor to set the brightness of.
 *
 *    # Returns
 *
 *    * `true` - If the brightness was set successfully.     * `false` - If the brightness was not set successfully.
 */
bool ddc_set_monitor_brightness(uint16_t percent,
                                const char *monitor_id);

/**
 *     Set the brightness of all monitors.
 *
 *    # Arguments
 *
 *    * `percent` - The brightness to set the monitor to.
 *
 *    # Returns
 *
 *    * `true` - If the brightness was set successfully.     * `false` - If the brightness was not set successfully.
 */
bool ddc_set_brightness(uint16_t percent);

#endif  /* DDC_HANDLER_H */
